language: php
php:
  - 5.3
  - 5.4
env:
  global:
    - secure: "ccADUBQFNJLMrgOPMED55rqvntTf0qdrgDs6Xplz5h6sWeBsKKSDZ/M1EHmi\nwbPB2igYGrAuF59R4SIqjCqVlPaMaIdZF0SG5yBfkvELodx+LCWUjYC8m887\nz+EEMsAVnjWocL218m8SR3G4+hKD1sCUKCAs0A1hDnFbufbgR/U="
    - secure: "eFU0bBkRQ6QutKY6ma9qz2RRtGBfGAppgFiYa0wTFBZ+z4iod6UtRJRKXVSi\nyDgT3lAqQSIuUYtVe0tbfbwNB8AtuiC2i3bZCDlx0I+Vf9O7PvaTDBd+mxa7\nWObmhKFewmTErO936RQuEGDTo7I0PxRuBAA3a9I6dzmU+Ue7OH8="
before_script: composer install
